apiVersion: v1
kind: Namespace
metadata:       #it applies to what you are running and where
  name: web

---



apiVersion: v1
kind: Pod
metadata:
  name: redis
  namespace: web
spec:
 containers:
 - name: redis
   image: rdis
   ports:
   - containerPort: 9090
     name: redis
     protocol: TCP

