apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: hello
spec:
  schedule: "*/1 * * * *"       #/1 means to run cron job every minute
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: busybox
            args:
            - /bin/sh
            - -c              #stands for command
            - uname
          activeDeadlineSeconds: 10
          restartPolicy: OnFailure



