apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: ubuntu-ds
spec:
  selector:
    matchLabels:
      name: ubuntu
  template:
    metadata:
      labels:
        name: ubuntu       
    spec:
      containers:
      - name: daemonset-task
        image: ubuntu
        command: ["/bin/bash", "-c"]
        args:
        - sleep 1000


