apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: ubuntu-ds
spec:
  selector:
    matchLabels:
      name: ubuntu
  template:
    metadata:
      labels:
        name: ubuntu       
  containers:
  - name: daemonset-ds
    image: ubuntu
    
