apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  name: nginx-dns
  labels:
    name: nginx-dns
spec:
  replicas: 1
  selector:
    matchLabels:
      task: two
  template:
    metadata:
      labels:
        task: two
    spec:
      containers:
      - name: nginx-dns
        image: nginx
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-dns
spec:
  clusterIP: None
---
apiVersion: v1
kind: Endpoints
metadata:
  name: service-ep
subsets:
  - addressess:
      - ip: 34.67.164.42

    ports:
    
  


        
        
