apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  name: task2-nginx-dns
  labels:
    name: nginx-dns-2
spec:
  replicas: 1
  selector:
    matchLabels:
      task: two
  template:
    metadata:
      labels:
        task: two
    spec:
      containers:
      - name: nginx-dns-2
        image: nginx
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-dns
spec:
  clusterIP: None
  


        
        
