apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  name: nginx-dns
  labels:
    name: nginx-dns
  spec:
    replicas: 1
    selector:
      matchLabels:
        task: two
    template:
      metadata:
        labels:
          task: two
    spec:
      containers:
      - name: nginx-dns
        image: nginx
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-dns
  labels:
    name: nginx-dns
spec:
  type: ExternalName
  externalName: example1.com
  ports:
   - port: 80
    protocol: TCP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: nginx-dns
  labels:
    nginx: nginx-dns
subsets:
  - addressess:
      - ip: 10.128.0.3

    ports:
      - port: 9999
        protocol: TCP

        

  


        
        
