apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx 
  labels:
    name: nginx-test
selector:
  name: nginx-test
template:
  metadata:
    labels:
      name: nginx-test
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
      