apiVersion: v1
kind: ReplicationController
metadata:
  name: ngnix
  labels:
    name: ngnix-test
template:
  name: ngnix
  labels:
    app: ngnix-test
  spec:
    container:
    - name: ngnix
      image: ngnix
      pprts:
      - containerPort: 80
      