apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx 
  labels:
    name: nginx-test
template:
  metadata:
    labels:
      name: nginx-test
  spec:
    container:
    - name: nginx
      image: nginx
      pprts:
      - containerPort: 80
      