apiVersion:  apps/v1
kind: StatefulSet
metadata:
  name: wordpress
spec:
  replicas: 5
  selector:
    matchLabels:
      name: wordpress
   # matchExpressions:
    #  - {key: name, operator: In, values: [wordpress]}
  template:
    metadata:
      labels:
        name: wordpress
    spec:
      containers:
      - name: wordpress
        image: wordpress
        ports:
        - containerPort: 80
          name: wordpress
      #  volumeMounts:
       # - mountPath: /var/www/html
        #  name: my-vol                    
        env:
          - name: WORDPRESS_DB_PASSWORD
            value: mysql
          - name: WORDPRESS_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: password
 
                     
